name 'neh-webserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures neh-webserver'
long_description 'Installs/Configures neh-webserver'
version '0.2.0'
